r2:
  bucket: cs611-project

backfill:
  start_date: "1983-01-01"
  end_date: "2024-12-31"

landing:
  path: "s3a://cs611-project/landing"
  legal_docs:
    folder: "legal_docs"
    file_prefix: "EurLex_snapshot_"
    tables:
      legal_docs_raw:
        partition_col: snapshot_date
  wiki_docs:
    folder: "wiki_docs"
    filename: "wiki.csv"
    tables:
      wiki_docs_raw:
        partition_col: snapshot_date

bronze:
  path: "s3a://cs611-project/bronze"
  tables:
    legal_docs_raw:
      path: legal_docs_raw
      partition_col: snapshot_date
    wiki_docs_raw:
      path: wiki_docs_raw
      partition_col: snapshot_date

silver:
  path: "s3a://cs611-project/silver"
  tables:
    legal_docs_processed:
      path: legal_docs_processed
      partition_col: snapshot_date
    wiki_docs_processed:
      path: wiki_docs_processed
      partition_col: snapshot_date

gold:
  path: "s3a://cs611-project/gold"
  tables:
    ngram_count:
      path: ngram_count
      partition_col: snapshot_date
    tfidf_features_train:
      path: tfidf_features_train
    tfidf_features_val_test_oot:
      path: tfidf_features_val_test_oot
    pos_counts:
      path: pos_counts
      partition_col: snapshot_date
    pos_counts_wiki:
      path: pos_counts_wiki
    dcw_features_train:
      path: dcw_features_train
    dcw_features_val_test_oot:
      path: dcw_features_val_test_oot
    embeddings:
      path: embeddings
      partition_col: snapshot_date
    embeddings_wiki:
      path: embeddings_wiki
    label_store:
      path: label_store
      partition_col: snapshot_date
    labels:
      path: labels
    model_prediction:
      path: model_prediction
    inference_features:
      path: inference_features
    batch_inference:
      path: batch_inference
    published_predictions:
      path: published_predictions
    runs:
      path: runs

model_bank:
  path: "s3a://cs611-project/model_bank"
  runs:
    path: runs
  aliases:
    path: aliases
  deployment_history:
    path: deployment/history
  features_extractor:
    tfidf:
      path: features_extractor/tfidf
      vocab_file: gold_vocab_1_3.json
      meta_file: gold_meta_1_3.json
    dcw_score: features_extractor/dcw_score
    dcw_train_doc_ids: features_extractor/dcw_train_doc_ids
