r2:
  bucket: cs611-project

backfill:
  start_date: "1983-01-01"
  end_date: "2024-12-31"

landing:
  path: "s3a://cs611-project/landing"
  legal_docs:
    folder: "legal_docs"
    file_prefix: "EurLex_snapshot_"
    tables:
      legal_docs:
        partition_col: snapshot_date
  wiki_docs:
    folder: "wiki_docs"
    filename: "wiki.csv"
    tables:
      wiki_docs:
        partition_col: snapshot_date

bronze:
  path: "s3a://cs611-project/bronze"
  legal_docs:
    tables:
      legal_docs:
        table_dir: legal_docs_raw
        partition_col: snapshot_date
  wiki_docs:
    tables:
      wiki_docs:
        table_dir: wiki_docs_raw
        partition_col: snapshot_date
